

Create Proc Reference.[usp_Populate_PostArea]
as
	Set nocount on 
	;

	Truncate table Reference.PostArea
	;

	insert	Reference.PostArea (PostArea,  PostAreaName) values ('AB','Aberdeen')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('AL','St Albans')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('B','Birmingham')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('BA','Bath')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('BB','Blackburn')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('BD','Bradford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('BH','Bournemouth')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('BL','Bolton')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('BN','Brighton')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('BR','Bromley')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('BS','Bristol')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('BT','Belfast')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CA','Carlisle')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CB','Cambridge')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CF','Cardiff')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CH','Chester')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CM','Chelmsford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CO','Colchester')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CR','Croydon')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CT','Canterbury')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CV','Coventry')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('CW','Crewe')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('DA','Dartford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('DD','Dundee')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('DE','Derby')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('DG','Dumfries')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('DH','Durham')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('DL','Darlington')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('DN','Doncaster')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('DT','Dorchester')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('DY','Dudley')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('E','East London')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('EC','East Central London')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('EH','Edinburgh')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('EN','Enfield')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('EX','Exeter')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('FK','Falkirk')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('FY','Blackpool')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('G','Glasgow')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('GL','Gloucester')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('GU','Guildford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('HA','Harrow')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('HD','Huddersfield')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('HG','Harrogate')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('HP','Hemel Hempstead')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('HR','Hereford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('HS','Hebrides')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('HU','Hull')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('HX','Halifax')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('IG','Ilford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('IP','Ipswich')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('IV','Inverness')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('KA','Kilmarnock')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('KT','Kingston upon Thames')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('KW','Kirkwall')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('KY','Kirkcaldy')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('L','Liverpool')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('LA','Lancaster')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('LD','Llandrindod Wells')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('LE','Leicester')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('LL','Llandudno')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('LN','Lincoln')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('LS','Leeds')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('LU','Luton')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('M','Manchester')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('ME','Medway')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('MK','Milton Keynes')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('ML','Motherwell')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('N','North London')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('NE','Newcastle upon Tyne')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('NG','Nottingham')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('NN','Northampton')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('NP','Newport')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('NR','Norwich')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('NW','North West London')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('OL','Oldham')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('OX','Oxford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('PA','Paisley')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('PE','Peterborough')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('PH','Perth')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('PL','Plymouth')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('PO','Portsmouth')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('PR','Preston')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('RG','Reading')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('RH','Redhill')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('RM','Romford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('S','Sheffield')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SA','Swansea')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SE','South East London')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SG','Stevenage')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SK','Stockport')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SL','Slough')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SM','Sutton[1]')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SN','Swindon')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SO','Southampton')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SP','Salisbury')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SR','Sunderland')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SS','Southend-on-Sea')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('ST','Stoke-on-Trent')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SW','South West London')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('SY','Shrewsbury')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('TA','Taunton')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('TD','Tweeddale')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('TF','Telford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('TN','Tunbridge Wells')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('TQ','Torquay')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('TR','Truro')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('TS','Teesside')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('TW','Twickenham')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('UB','Southall[1]')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('W','West London')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('WA','Warrington')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('WC','West Central London')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('WD','Watford')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('WF','Wakefield')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('WN','Wigan')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('WR','Worcester')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('WS','Walsall')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('WV','Wolverhampton')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('YO','York')
	insert	Reference.PostArea (PostArea,  PostAreaName) values ('ZE','Lerwick')
	;

	if not exists (Select * from SystemControl.ReferenceControl where ReferenceTableName = 'PostArea')
	begin
		insert	SystemControl.ReferenceControl ([ReferenceTableName], [MaxReferenceSK], [LastAllocatedReferenceSK])
		Select	'PostArea', max(PostAreaSK), 1
		from	Reference.PostArea
	end
	else 
	begin
		Update	SystemControl.ReferenceControl
		set		[MaxReferenceSK] = (Select max(PostAreaSK) from Reference.PostArea)
		where	ReferenceTableName = 'PostArea'
	end